### PR TITLE
Support using childContextTypes and contextTypes

### PR DESCRIPTION
**Pull request by gavacho**

### CODE REVIEW

**Comment by gavacho** [comment]
Hi @gcanti!  I started using the new context affordances of react.  They're very similar to propTypes so I wanted to use tcomb-react.  I'm not sure this is the way you would want to implement support but it's working for me!

**Comment by gcanti** [comment]
Hi @gavacho
I'm not a big fan of `contextType`s. Actually I firmly avoid them, so I didn't notice the issue with the strict check, thanks for pointing out.

I'm ok with adding support and thanks for your PR: in the additional props check, besides the `__strict__` key, we should exclude the `__subtype__` key for the same reason I guess.

**Comment by gavacho** [comment]
I've updated the PR to exclude the `__subtype__` key in addition to the `__strict__` key

**Comment by gcanti** [comment]
Great, thanks @gavacho :+1:

**Pull request merged**
